version: '3.8'
services:
  typesense:
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_API_KEY=local-typesense-api-key
    entrypoint: sh -c "/opt/typesense-server --enable-cors"
    ports:
      - '8108:8108'
    volumes:
      - ./typesense-data:/data
